"""Markdown report generator."""

from ..models import TestReport


def generate_report(report: TestReport, output_path: str):
    """Generate Markdown report file."""
    lines = []

    # Header
    lines.append("# AKS Spot Test Report\n")
    lines.append(f"**Cluster:** {report.cluster_name}\n")
    lines.append(f"**Date:** {report.timestamp.strftime('%Y-%m-%d %H:%M:%S')}\n")
    lines.append(f"**Duration:** {_format_duration(report.duration_seconds)}\n")
    lines.append(f"**Run ID:** {report.run_id}\n")
    lines.append("\n---\n\n")

    # Executive Summary
    lines.append("## Executive Summary\n\n")
    status_emoji = "✅" if report.failed == 0 else "⚠️"
    lines.append(f"{status_emoji} **Overall Result:** {'PASS' if report.failed == 0 else 'FAIL'} ({report.pass_rate:.2f}% pass rate)\n\n")
    lines.append(f"- **Total Tests:** {report.total_tests}\n")
    lines.append(f"- **Passed:** {report.passed} ✅\n")
    lines.append(f"- **Failed:** {report.failed} ❌\n")
    lines.append(f"- **Skipped:** {report.skipped} ⏭️\n\n")

    # Framework Breakdown
    lines.append("### Framework Breakdown\n\n")
    lines.append("| Framework | Total | Passed | Failed | Skipped | Pass Rate |\n")
    lines.append("|-----------|-------|--------|--------|---------|-----------|\ n")
    for framework, stats in report.framework_summary.items():
        total = stats['total']
        passed = stats['passed']
        pass_rate = (passed / total * 100) if total > 0 else 0.0
        lines.append(f"| {framework.capitalize()} | {total} | {passed} | {stats['failed']} | {stats['skipped']} | {pass_rate:.0f}% |\n")
    lines.append("\n")

    # Category Breakdown
    lines.append("### Category Breakdown\n\n")
    lines.append("| Category | Total | Passed | Failed | Skipped |\n")
    lines.append("|----------|-------|--------|--------|---------|\ n")
    for category, stats in sorted(report.category_summary.items()):
        lines.append(f"| {category} | {stats['total']} | {stats['passed']} | {stats['failed']} | {stats['skipped']} |\n")
    lines.append("\n---\n\n")

    # Cluster Health
    lines.append("## Cluster Health\n\n")
    lines.append(f"**Eviction Rate:** {report.eviction_rate_per_hour:.1f} evictions/hour ({len(report.eviction_events)} total during test)\n")
    lines.append(f"**Remediation:** {len(report.remediation_actions)} actions taken\n\n")

    if report.initial_state and report.final_state:
        lines.append("### Node Distribution\n\n")
        lines.append("| Metric | Before | After | Change |\n")
        lines.append("|--------|--------|-------|--------|\ n")
        lines.append(f"| Total Nodes | {report.initial_state.total_nodes} | {report.final_state.total_nodes} | {report.final_state.total_nodes - report.initial_state.total_nodes:+d} |\n")
        lines.append(f"| Spot Nodes | {report.initial_state.spot_nodes} | {report.final_state.spot_nodes} | {report.final_state.spot_nodes - report.initial_state.spot_nodes:+d} |\n")
        lines.append(f"| Ready Nodes | {report.initial_state.ready_nodes} | {report.final_state.ready_nodes} | {report.final_state.ready_nodes - report.initial_state.ready_nodes:+d} |\n")
        lines.append("\n")

    # Failed Tests
    if report.top_failures:
        lines.append("## Failed Tests\n\n")
        for i, failure in enumerate(report.top_failures, 1):
            lines.append(f"### {i}. {failure.test_id}: {failure.name} ❌\n\n")
            lines.append(f"**Framework:** {failure.framework}\n")
            lines.append(f"**Category:** {failure.category}\n")
            lines.append(f"**Duration:** {failure.duration_seconds:.1f}s\n\n")
            if failure.error_message:
                lines.append("**Error:**\n```\n")
                lines.append(failure.error_message[:500])  # Truncate long errors
                lines.append("\n```\n\n")
            if failure.reproduce_commands:
                lines.append("**Reproduce:**\n```bash\n")
                for cmd in failure.reproduce_commands:
                    lines.append(f"{cmd}\n")
                lines.append("```\n\n")

    # Remediation Actions
    if report.remediation_actions:
        lines.append("## Remediation Actions\n\n")
        lines.append("| Time | Action Type | Target | Status | Details |\n")
        lines.append("|------|-------------|--------|--------|---------|\ n")
        for action in report.remediation_actions:
            status = "✅ Success" if action.success else "❌ Failed"
            lines.append(f"| {action.timestamp.strftime('%H:%M:%S')} | {action.action_type} | {action.target} | {status} | {action.details} |\n")
        lines.append("\n")

    # Footer
    lines.append("---\n\n")
    lines.append("*Generated by `aks-spot-test` v1.0.0*\n")

    # Write file
    with open(output_path, 'w') as f:
        f.writelines(lines)


def _format_duration(seconds: float) -> str:
    """Format duration in human-readable form."""
    minutes = int(seconds // 60)
    secs = int(seconds % 60)
    return f"{minutes}m {secs}s"
